### ISSUE TITLE
[✨feat] 사용 가능한 모든 통화를 조회하는 API 개발2

### ISSUE THREAD

**Issue by jsoonworld** [Team-FoodiePass/FoodiePass-Server#1]
## ⚙️ ISSUE
- 사용 가능한 모든 통화를 조회하는 API를 개발합니다.

## 📄 To-Do
- [ ] 관련 Domain 을 구현합니다.
- [ ] 관련 DTO를 구현합니다.
- [ ] 관련 Service를 구현합니다.
